### ISSUE TITLE
http server

### ISSUE THREAD

**Issue by karissa** [karissa/dat-server#2]
have an http inside to ping http://.../<link>/<entry> and get the file contents back over http, with byte ranges

**Comment by maxogden** [comment]
@mafintosh and i were talking about this, and at first we thought we could use a single tcp server/port to host both the dat tcp protocol as well as an http gateway. but upon further discussion we realized that would make it very difficult to put dat behind an https gateway (such as nginx) so we now think the easier way is to just use one tcp server/port for the dat protocol and another for the http gateway
